### ISSUE TITLE
When do you plan to release the data?

### ISSUE THREAD

**Issue by charlesCXK** [wangyida/forknet#1]
Hi, thank you for your sharing.  There are many commands like 
```python2 data/depthbin2npy.py -s /media/wangyida/HDD/database/SUNCGtrain_1001_2000  -tv /media/wangyida/HDD/database/SUNCG_Yida/train/voxel_semantic_npy &```
but there is no data or download-link in the repo. Could you supply the download link of the train/test data? Thank you!

**Comment by wangyida** [comment]
Hi as the official SUNCG dataset are not available online now, I suggest you to use other dataset such as ScanNet and ScanComplete. Our data are processed from binary files of SUNCG volumetric data, you can also use those data directly with our rendering script in data sub-folder

**Comment by charlesCXK** [comment]
Thanks!

**Comment by wangyida** [comment]
By the way, the ShapeNet data could be downloaded from the 3D RecGAN repo.
