### ISSUE TITLE
Some problems in the test phase using the pretrained model

### ISSUE THREAD

**Issue by lt-ice** [wangyida/forknet#6]
Hello,
When I tested five pictures in SUNCG, I found that it was mostly empty in result.
I have successfully generated these related files in depth_tsdf_camera_npy, surface_semantic_npy, and voxel_semantic_npy . 
So what do you think is the reason why it's mostly empty ? Can this be a problem with the pre-training model? And what's the difference between a small model and a large one ?
Looking forward to your reply
Best wishes

The results are as follows:
Completion
IoU of empty:0.919
IoU of objec:0.01
IoU average: 0.464

Geometric segmentation
IoU of empty:0.0
/home/lt/Documents/ForkNet/forknet-master/evaluate.py:45: RuntimeWarning: invalid value encountered in double_scalars
  IoU_calc = np.round(child / mother, 3)
IoU of ceili:nan
IoU of floor:nan
IoU of  wall:nan
IoU of windo:nan
IoU of chair:nan
IoU of   bed:nan
IoU of  sofa:nan
IoU of table:nan
IoU of   tvs:nan
IoU of furni:nan
IoU of objec:nan
IoU average: nan

Generative segmentation
IoU of empty:0.0
IoU of ceili:nan
IoU of floor:nan
IoU of  wall:nan
IoU of windo:nan
IoU of chair:nan
IoU of   bed:nan
IoU of  sofa:nan
IoU of table:nan
IoU of   tvs:nan
IoU of furni:nan
IoU of objec:nan
IoU average: nan

Geometric semantic completion
IoU of empty:0.956
IoU of ceili:0.0
IoU of floor:0.0
IoU of  wall:0.0
IoU of windo:0.0
IoU of chair:0.0
IoU of   bed:0.0
IoU of  sofa:nan
IoU of table:0.0
IoU of   tvs:0.0
IoU of furni:0.0
IoU of objec:0.0
IoU average: nan

Generative semantic completion
IoU of empty:0.95
IoU of ceili:0.033
IoU of floor:0.0
IoU of  wall:0.0
IoU of windo:0.0
IoU of chair:0.0
IoU of   bed:0.0
IoU of  sofa:nan
IoU of table:0.0
IoU of   tvs:0.0
IoU of furni:0.0
IoU of objec:0.0
IoU average: nan

Solid generative semantic completion
IoU of empty:0.952
IoU of ceili:0.028
IoU of floor:0.0
IoU of  wall:0.0
IoU of windo:0.0
IoU of chair:0.0
IoU of   bed:0.0
IoU of  sofa:nan
IoU of table:0.0
IoU of   tvs:0.0
IoU of furni:0.0
IoU of objec:0.0
IoU average: nan

**Comment by wangyida** [comment]
As you can see that the *nan* indicates that the results are not just empty, I think the range of values in depth_tsdf_camera_npy is wrongly given. You can have a check for whether the camera intrinsics produce reasonale TSDF surfaces, you can visualise it with point cloud

**Comment by lt-ice** [comment]
Thank you.
Following your instructions, I've visualized the input TSDF. And it was found to be abnormal. I fixed the problem, but the result is still incorrect. 
From the results, I found that the pred_ssc is normal, but pred_full and pred_surf are abnormal.
So what do you think is the reason?
Looking forward to your reply.

The results are as follows:
Completion
IoU of empty:0.876
IoU of objec:0.013
IoU average: 0.444

Geometric segmentation
IoU of empty:0.026
IoU of ceili:0.971
IoU of floor:0.868
IoU of  wall:0.666
IoU of windo:0.676
IoU of chair:0.43
IoU of   bed:0.027
IoU of  sofa:0.0
IoU of table:0.295
IoU of   tvs:0.308
IoU of furni:0.33
IoU of objec:0.158
IoU average: 0.43

Generative segmentation
IoU of empty:0.032
IoU of ceili:0.023
IoU of floor:0.0
IoU of  wall:0.0
IoU of windo:0.0
IoU of chair:0.0
IoU of   bed:0.0
/home/lt/Documents/ForkNet/forknet-master/evaluate.py:45: RuntimeWarning: invalid value encountered in double_scalars
  IoU_calc = np.round(child / mother, 3)
IoU of  sofa:nan
IoU of table:0.0
IoU of   tvs:0.0
IoU of furni:0.0
IoU of objec:0.0
IoU average: nan

Geometric semantic completion
IoU of empty:0.975
IoU of ceili:0.954
IoU of floor:0.622
IoU of  wall:0.502
IoU of windo:0.653
IoU of chair:0.345
IoU of   bed:0.213
IoU of  sofa:0.0
IoU of table:0.154
IoU of   tvs:0.303
IoU of furni:0.293
IoU of objec:0.131
IoU average: 0.379

Generative semantic completion
IoU of empty:0.956
IoU of ceili:0.016
IoU of floor:0.0
IoU of  wall:0.0
IoU of windo:0.0
IoU of chair:0.0
IoU of   bed:0.0
IoU of  sofa:nan
IoU of table:0.0
IoU of   tvs:0.0
IoU of furni:0.0
IoU of objec:0.0
IoU average: nan

Solid generative semantic completion
IoU of empty:0.958
IoU of ceili:0.005
IoU of floor:0.0
IoU of  wall:0.0
IoU of windo:0.0
IoU of chair:0.0
IoU of   bed:0.0
IoU of  sofa:nan
IoU of table:0.0
IoU of   tvs:0.0
IoU of furni:0.0
IoU of objec:0.0
IoU average: nan

**Comment by wangyida** [comment]
So at least the 'Geometric semantic completion' makes sense, which dataset are you evaluating on? I updated the model to solve some NaN issues, can you try again? Notice that you should use ' --discriminative True'
I tested some samples in SUNCG, it should be something like:
Geometric semantic completion
IoU of empty:0.969
IoU of ceili:0.79
IoU of floor:0.674
IoU of  wall:0.334
IoU of windo:0.196
IoU of chair:0.103
IoU of   bed:0.467
IoU of  sofa:0.436
IoU of table:0.206
IoU of   tvs:0.155
IoU of furni:0.29
IoU of objec:0.167
IoU average: 0.347

Generative semantic completion
IoU of empty:0.968
IoU of ceili:0.671
IoU of floor:0.671
IoU of  wall:0.334
IoU of windo:0.146
IoU of chair:0.027
IoU of   bed:0.459
IoU of  sofa:0.448
IoU of table:0.116
IoU of   tvs:0.001
IoU of furni:0.277
IoU of objec:0.181
IoU average: 0.303

Solid generative semantic completion
IoU of empty:0.968
IoU of ceili:0.666
IoU of floor:0.675
IoU of  wall:0.333
IoU of windo:0.155
IoU of chair:0.016
IoU of   bed:0.457
IoU of  sofa:0.453
IoU of table:0.123
IoU of   tvs:0.006
IoU of furni:0.284
IoU of objec:0.196
IoU average: 0.306

Did you retrained the model? I think now the encoder works, but the parametric model in your decoder is not trained.

**Comment by lt-ice** [comment]
Sorry for my late response and thank you for your help.
I have retained the model on SUNCGtrain_501_1000  and I got a much better result than the one shown above when evaluating on the dataset of SUNCG. 
Besides, I have compared your work to sscnet and vvnet, it's really a great job.
Thanks again for your help and I will continue to learn from you.

**Comment by wangyida** [comment]
You're welcome, I updated the model again with results like:
solidly decoded
IoU of emp: 97.2 -0.1
IoU of ceil: 88.7 +4.4
IoU of floor: 70.7 +1.0
IoU of wall: 40.2 +0.1
IoU of wind: 46.9 +3.3
IoU of chair: 56.9 +3.3
IoU of bed: 58.0 +1.1
IoU of sofa: 76.6 +10.3
IoU of table: 49.8 +3.7
IoU of tvs: 70.1 +0.2
IoU of furn: 25.9 +2.2
IoU of obj: 12.0 +0.3
IoU average: 54.2

**Comment by lt-ice** [comment]
Wow, it's great and I will have a try.
