### ISSUE TITLE
请教数据处理相关的问题

### ISSUE THREAD

**Issue by Alenbeinsane** [wangyida/forknet#8]
hi yida, 我是3D-cv领域的新手，想通过你的项目学习一下。但是在数据准备时发现suncg的数据我已经没有办法获取到了，因此我准备了NYU-V2的数据（labeled-dataset: 2.5GB），并且我发现可以从这份数据里提取出depth-image和rgb_image，然后使用open3d的库可以准备出tsdf的ply格式的数据。我阅读你的数据处理脚本，发现你能很方便的就统一处理，但是我不太理解时怎么做的，希望能得到你的解答，谢谢！

**Comment by Alenbeinsane** [comment]
> hi yida, 我是3D-cv领域的新手，想通过你的项目学习一下。但是在数据准备时发现suncg的数据我已经没有办法获取到了，因此我准备了NYU-V2的数据（labeled-dataset: 2.5GB），并且我发现可以从这份数据里提取出depth-image和rgb_image，然后使用open3d的库可以准备出tsdf的ply格式的数据。我阅读你的数据处理脚本，发现你能很方便的就统一处理，但是我不太理解时怎么做的，希望能得到你的解答，谢谢！

已经在其他issue中找到了答案:)

**Comment by wangyida** [comment]
这个问题TSDF的volume生成比较重要，必要的时候你可以转化成点云看看输入输出对不对得上，我的evaluate.py里面有些怎么把volume data转成点云，这样方便查看你训练数据中存在的问题
